# Page tree
docs_dir: .
nav:
  - Basics:
    - Getting Started: getting-started.md
    - Architecture: applaunchpad-architecture.md
    - FAQ: faq.md
    - Versions: versions.md
  - AppLaunchpad Core: 
    - Quick setup: application-setup.md
    - General settings: general-settings.md 
    - UI features: applaunchpad-ux-features.md 
    - Lifecycle hooks: lifecycle-hooks.md 
    - Internationalization: i18n.md 
    - Web Component: web-component.md 
  - Navigation: 
    - Basic navigation: navigation-configuration.md
    - Advanced navigation: navigation-advanced.md
    - Global search: global-search.md
    - User settings: user-settings.md
    - Navigation parameters reference: navigation-parameters-reference.md
  - Authorization: 
    - Authorization configuration: authorization-configuration.md
    - Authorization events: authorization-events.md
  - AppLaunchpad Client: 
    - AppLaunchpad Client Installation: applaunchpad-client-setup.md
    - Framework support libraries: framework-support-libraries.md
    - Advanced configuration options: advanced-options-applaunchpad-client.md
  - API Reference: 
    - AppLaunchpad Core API: applaunchpad-core-api.md
    - AppLaunchpad Client API: applaunchpad-client-api.md
  - Advanced: 
    - Advanced scenarios: advanced-scenarios.md
    - Core/Client Communication: communication.md
  - Examples:
    - Navigation configuration example: navigation-configuration-example.md